name: CI Build

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - ".idea/"
      - "doc/*"
      - "*.md"
      - "app/src/assets/**"
      - ".github/workflows/crowdin.yml"
      - "crowdin.yml"
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - ".idea/"
      - "doc/*"
      - "*.md"
      - "app/src/assets/**"
      - "crowdin.yml"
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest
    name: Build App
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Create Sign File
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          touch signing.properties
          sudo apt install python
          python sign.py >> signing.properties
          echo keyAlias="${{ secrets.ALIAS }}" >> signing.properties
          echo storeFile=../key.jks >> signing.properties
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > key.jks

      - name: Build with Gradle (Canary)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        shell: bash
        run: |
          ./gradlew assembleCanary
          echo "IS_DEBUG=false" >> $GITHUB_ENV

      - name: Build with Gradle (Debug)
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          ./gradlew assembleDebug
          echo "IS_DEBUG=true" >> $GITHUB_ENV

      - name: Find APKs
        run: |
          if [ ${{ env.IS_DEBUG }} = true ]; then
            APK_FILE=$(find app/build/outputs/apk/debug -name '*.apk')
          else
            APK_FILE=$(find app/build/outputs/apk/canary -name '*.apk')
          fi
          echo "APK_FILE=$APK_FILE" >> $GITHUB_ENV
          echo "APK_FILE_NAME=$(basename $APK_FILE .apk)" >> $GITHUB_ENV

      - name: Show APKs SHA256
        if: success()
        run: |
          echo "### Build Success" >> $GITHUB_STEP_SUMMARY
          echo "|Artifact|SHA256|" >> $GITHUB_STEP_SUMMARY
          echo "|:---:|:---|" >> $GITHUB_STEP_SUMMARY
          APK_SHA256=($(sha256sum ${{ env.APK_FILE }}))
          if [ ${{ env.IS_DEBUG }} = true ]; then
            echo "|Debug|$APK_SHA256" >> $GITHUB_STEP_SUMMARY
          else
            echo "|Canary|$APK_SHA256" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_FILE_NAME }}
          path: ${{ env.APK_FILE }}
          compression-level: 9
