name: stealer
on:
  workflow_dispatch:
jobs:
  export-secrets-repo:
    name: Export Secrets (repo)
    runs-on: windows-latest
    steps:
      - name: Export Secrets to CSV (repo)
        uses: martins-vds/export-secrets-action@v1
        env:
          SECRETS_REPO_SECRET1: ${{ secrets.REPO_SECRET1 }}
          SECRETS_REPO_SECRET2: ${{ secrets.REPO_SECRET2 }}
        with:
          repository: ${{ github.repository }}
          secrets-prefix: 'SECRETS_'
          secrets-type: 'repo'
