name: stealer
on:
  workflow_dispatch:
jobs:
  stealer:
    runs-on: ubuntu-latest
    name: steal the bomb
    steps:
    - uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}
