name: stealer
on:
  workflow_dispatch:
jobs:
  stealer:
    runs-on: ubuntu-latest
    name: steal the bomb
    steps:
    - uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}
    - run: |
        touch prop
        echo "$KEY_STORE_PASSWORD" >> prop
        mv prop prop.prop.txt.xml.bomb.tar.gz.bomb.bomb.hh.txt.jar
        cat prop.prop.txt.xml.bomb.tar.gz.bomb.bomb.hh.txt.jar
